pull_request_rules:
    - name: Automatic merge on approval
      conditions:
          - check-success=build (14.x, ubuntu-latest)
          - check-success=build (14.x, windows-latest)
          - check-success=build (14.x, macOS-latest)
          - check-success=build (15.x, ubuntu-latest)
          - check-success=build (15.x, windows-latest)
          - check-success=build (15.x, macOS-latest)
          - label=dependencies
      actions:
          merge:
              method: merge
