name: Node.js CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
    schedule:
        - cron: "0 0 * * *" # Every day

jobs:
    build:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                node-version: [14.x, 15.x, 16.x]
                os: [ubuntu-latest, windows-latest, macOS-latest]

        name: ${{ matrix.node-version }} on ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}

            - run: yarn install
            - run: yarn run build
